//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yacht.DAL.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yacht_Details
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Cover_Img_Url { get; set; }
        public Nullable<bool> Isavaible { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Create_by { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<System.DateTime> Delete_date { get; set; }
    }
}
