//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yacht.DAL.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yachts_Images
    {
        public long Id { get; set; }
        public Nullable<long> Yacht_Id { get; set; }
        public string Image_Url { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created_date { get; set; }
        public Nullable<long> Created_by { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<long> Updated_By { get; set; }
        public Nullable<System.DateTime> Deleted_date { get; set; }
        public Nullable<long> Deleted_by { get; set; }
    
        public virtual Tbl_Yacht_Details Tbl_Yacht_Details { get; set; }
    }
}
